name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  seek-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          COOKBOOK_DRAFT: ${{ secrets.COOKBOOK_DRAFT }}
        run: npm run test
      - name: build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          COOKBOOK_DRAFT: ${{ secrets.COOKBOOK_DRAFT }}
        with:
          command: npm run test:e2e
          start: npm run server:test
          wait-on: "http://localhost:3001"
          wait-on-timeout: 120
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stormy-shore-69938"
          heroku_email: jaakko.hurtta@outlook.com
          healthcheck: "https://stormy-shore-69938.herokuapp.com/health"
          delay: 1
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: GitHub tag bump
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
